"""
Log schema for Interpretation Gap simulation.
Every run produces a deterministic, hashable log with Negative Proof records.
"""
from typing import List, Dict, Any, Optional, TYPE_CHECKING
from pydantic import BaseModel, Field

if TYPE_CHECKING:
    from sim.core.ajt_record import AJTRecord


class Candidate(BaseModel):
    """A candidate response generated by the LLM stub."""
    candidate_id: str
    proposal: str
    reason: str
    confidence: float = Field(ge=0.0, le=1.0)
    metadata: Dict[str, Any] = Field(default_factory=dict)

    class Config:
        # Ensure stable JSON serialization for hashing
        json_encoders = {float: lambda v: round(v, 4)}


class NegativeProof(BaseModel):
    """Record of a candidate that was blocked/rejected."""
    candidate_id: str
    blocked_candidate: str
    blocked_by_rule_id: str
    reason: str
    timestamp: Optional[str] = None  # Omit for deterministic comparisons

    class Config:
        json_encoders = {float: lambda v: round(v, 4)}


class DecisionBasis(BaseModel):
    """Explanation of how the final decision was made."""
    selected_candidate_id: Optional[str] = None
    applied_rule_ids: List[str] = Field(default_factory=list)
    reasoning: str
    final_action: str  # "allow", "deny", "override", etc.


class ReproInfo(BaseModel):
    """Information for reproducing this exact run."""
    seed: int
    deterministic: bool = True
    run_hash: str
    policy_hash: str


class SimulationLog(BaseModel):
    """Complete log of a single simulation run."""
    case_id: str
    prompt_id: str
    input_payload: Dict[str, Any]

    # Policy info
    policy_version: str
    policy_hash: str

    # Candidates and decision
    candidates: List[Candidate]
    decision: str
    decision_basis: DecisionBasis

    # Negative Proof
    negative_proof: List[NegativeProof] = Field(default_factory=list)

    # Reproducibility
    repro: ReproInfo

    # AI Judgment Trail (spec-compliant)
    # https://github.com/Nick-heo-eg/spec
    ajt: Optional[Any] = Field(
        default=None,
        description="AI Judgment Trail record (spec-compliant, optional)"
    )

    class Config:
        json_encoders = {float: lambda v: round(v, 4)}

    def to_canonical_json(self) -> str:
        """Serialize to canonical JSON with sorted keys for stable hashing."""
        import json
        return json.dumps(
            self.model_dump(exclude={'repro', 'ajt'}),  # Exclude runtime fields from hash input
            sort_keys=True,
            indent=2,
            ensure_ascii=False
        )
