"""
Auto-generated tests for sim/tests/__init__.py
Generated by echo-agent repo_executor
"""
import pytest

try:
    import sim
    _MODULE_AVAILABLE = True
except ImportError:
    _MODULE_AVAILABLE = False


def test_module_importable():
    """모듈 임포트 가능 여부 확인."""
    assert _MODULE_AVAILABLE, "모듈 임포트 실패: sim.tests.__init__"

